spring.application.name=product-service


spring.data.mongodb.uri=mongodb+srv://firkejagruti_db_user:Jagruti04121997@cluster-product.mhajgdp.mongodb.net/Cluster-Product

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

server.port=8082

inventory.service.url=http://localhost:8081/api/inventory